version: "2.0"
services:
   web:
      build: .
      ports:
        - "3000:3000"
      depends_on:
        - mongo
      environment:
        - CONTAINER_NAME=${CONTAINER_NAME}
   mongo:
      image: mongo
      ports:
         - "27027:27017"